### ISSUE TITLE
Does not want to work with API?

### ISSUE THREAD

**Issue by KalixtShawxo** [tien/pi-hole-connect#136]
I tried it with 2 different pi-holes, both of them scanned the  QR code but when I try to access the statistics,I get : 
"An error has occurred. Please check your Internet connection or whether the API has been set. " 

Since the QR code scans in with all asterisks I can't verify it's putting the right code and I haven't yet tried to type it in manually yet. 
Anything else I need to check? 
The home page does work to show the current numbers. 

Thanks.

**Comment by stolirocks1** [comment]
Same here. I have correct api key and statistics does not work. It never has.

**Comment by Tubeman-cell** [comment]
Same here. I have correct api key and statistics does not work. It never has. Perhaps you can write a work around?

**Comment by tien** [comment]
Hey guys, quite busy recently and haven't been able to spend much time going over this. I have just tested today with the latest pi.hole version and everything seems to be working fine for me?

**Comment by modem7** [comment]
> Hey guys, quite busy recently and haven't been able to spend much time going over this. I have just tested today with the latest pi.hole version and everything seems to be working fine for me?

Heya,

I've come across the same issue myself.

My current Docker setup is as follows:
```yaml
 #Pihole - Network wide adblocker, DNS cache and DHCP server
  pihole:
    image: pihole/pihole:latest
    container_name: Pihole
    hostname: PiHole-Master
    environment:
      # INTERFACE: $INTERFACE
      DNSMASQ_LISTENING: $DNSMASQ_LISTENING
      # ServerIP: $SERVER_IP
      PIHOLE_DNS_: $PIHOLE_DNS
      # VIRTUAL_HOST: $VIRTUAL_HOST
      WEB_BIND_ADDR: $SERVER_IP
      FTLCONF_LOCAL_IPV4: $SERVER_IP
      IPv6: false
      CORS_HOSTS: $CORS_HOSTS
      TZ: $TZ
      SKIPGRAVITYONBOOT: $SKIPGRAVITYONBOOT
      DNSSEC: $DNSSEC
      DNS_BOGUS_PRIV: $DNS_BOGUS_PRIV
      DNS_FQDN_REQUIRED: $DNS_FQDN_REQUIRED
      REV_SERVER: $REV_SERVER
      # DNSMASQ_USER: $DNSMASQ_USER
      PIHOLE_UID: $PUID
      PIHOLE_GID: $PGID
      WEB_UID: $PUID
      WEB_GID: $PGID
      REV_SERVER_TARGET: $REV_SERVER_TARGET
      REV_SERVER_CIDR: $REV_SERVER_CIDR
      REV_SERVER_DOMAIN: $REV_SERVER_DOMAIN
      CUSTOM_CACHE_SIZE: $CUSTOM_CACHE_SIZE
      WEBPASSWORD: $WEBPASSWORD
      WEBTHEME: default-dark
      FTLCONF_RATE_LIMIT: 0/0
      FTLCONF_MOZILLA_CANARY: $MOZILLA_CANARY
      FTLCONF_BLOCK_ICLOUD_PR: $BLOCK_ICLOUD_PR
    labels: 
      - "autoheal=true"
    cap_add:
      - CHOWN
      - SYS_NICE
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
    network_mode: "host"
    dns:
      - "127.0.0.1"
      - "9.9.9.9"
    depends_on:
      - dnscrypt-proxy
    volumes:
      - $USERDIR/Pihole/etc/pihole:/etc/pihole/
      - $USERDIR/Pihole/etc/dnsmasq:/etc/dnsmasq.d/
      # run `touch $USERDIR/Pihole/etc/logs/pihole.log` first unless you like errors
      - $USERDIR/Pihole/etc/logs/pihole.log:/var/log/pihole.log
      - $PIBACKUPDIR:/backup
      - $PISCRIPTS/piholebackup.sh:/scripts/piholebackup.sh:ro
    restart: always
    mem_limit: 2048m
    mem_reservation: 256m
```

App version 10.0
Docker Tag [2023.05.2](https://github.com/pi-hole/docker-pi-hole/releases/2023.05.2) 
Pi-hole [v5.17.1](https://github.com/pi-hole/pi-hole/releases/v5.17.1) 
FTL [v5.23](https://github.com/pi-hole/FTL/releases/v5.23) 
Web Interface [v5.20.1](https://github.com/pi-hole/AdminLTE/releases/v5.20.1)

I have two Pihole instances running in their own dedicated VMs, and they have this issue.

I'm able to see:
- Home
- Statistics
- Log

I have attempted to rescan the QR code as well as copy the API key manually.

If I go to `<serverIP>/admin/api.php` in a browser, I get the following:
```json
{"domains_being_blocked":1766285,"dns_queries_today":29922,"ads_blocked_today":7253,"ads_percentage_today":24.239691,"unique_domains":2203,"queries_forwarded":12275,"queries_cached":10174,"clients_ever_seen":30,"unique_clients":30,"dns_queries_all_types":29922,"reply_UNKNOWN":406,"reply_NODATA":3754,"reply_NXDOMAIN":702,"reply_CNAME":6673,"reply_IP":15274,"reply_DOMAIN":2758,"reply_RRNAME":3,"reply_SERVFAIL":24,"reply_REFUSED":0,"reply_NOTIMP":0,"reply_OTHER":0,"reply_DNSSEC":0,"reply_NONE":0,"reply_BLOB":328,"dns_queries_all_replies":29922,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1685240630,"relative":{"days":3,"hours":11,"minutes":18}}}
```
